const express = require('express');
const accountRouter = express.Router();
import { cache } from '../middleware/cache';
import AccountController from '../controller/controller.account';
import { handleError } from '../utils/response.error';
import { checkApiKey } from '../middleware/auth.Apikey';
import { authentication } from '../middleware/authentication';
import { authorization } from '../middleware/authorization';
import { Response } from 'express';
const accountController = new AccountController();
// accountRouter.use(checkApiKey);
accountRouter.get('/account', authorization(['admin']), (req: Request, res: Response) => {
    res.json('Hello! this is website API of cuongdepchai 😍😍😍');
});
accountRouter.post('/account/login', handleError(accountController.login));
accountRouter.post('/account/login-google', handleError(accountController.handleLoginWithGoogle));
accountRouter.post('/account/', checkApiKey, handleError(accountController.create));
accountRouter.post('/account/:id', checkApiKey, handleError(accountController.changePassword));
accountRouter.get('/account/confirm-code/:email', handleError(accountController.confirmCode));
accountRouter.post('/account/change-password/:email', authentication, handleError(accountController.forgetPassword));
export default accountRouter;
