@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InVzZXIxQGdtYWlsLmNvbSIsInJvbGUiOiJzaGlwcGVyIiwiaWF0IjoxNjg4MzQ5MjUxLCJleHAiOjE2ODg1MjIwNTF9.Ys5FYSDkRxO6NcF4BHeQTA34fvBF1JqsD9nk9fjNe4U
# GET http://localhost:3000/ts/search

GET http://localhost:3000/product?type=candy
Authorization: Bearer {{token}}
